name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # 注意：即使使用第三方构建工具，通常也需要先配置 JDK 环境
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Android project
        uses: vgaidarji/android-github-actions-build@v1.0.1
        with:
          # 这里的 args 就是你要执行的 gradle 命令
          args: "./gradlew assembleDebug"
